# Generated by Django 5.2.7 on 2026-03-16 15:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScanSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('duration', models.IntegerField(help_text='Scan duration in seconds')),
                ('device_count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_address', models.CharField(db_index=True, max_length=20)),
                ('rssi', models.CharField(max_length=10)),
                ('raw_data', models.TextField()),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('device_name', models.CharField(blank=True, max_length=255, null=True)),
                ('decoded_data', models.JSONField(blank=True, null=True)),
                ('scan_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='Scan.scansession')),
            ],
            options={
                'ordering': ['mac_address'],
            },
        ),
    ]
